---
services:
  casns:
    image: ghcr.io/casapps/casns:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
      - "443:443"
      - "853:853"
    volumes:
      - './volumes/config:/config:z'
      - './volumes/data:/data:z'
    environment:
      - MODE=production
